name: inject_dartpad
publish_to: none

resolution: workspace
environment:
  sdk: ^3.11.0

dependencies:
  html_unescape: ^2.0.0
  web: ^1.1.1

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  build_runner: ^2.11.0
  build_web_compilers: ^4.4.11
  path: ^1.9.1
  test: ^1.28.0
  webdev: ^3.8.0
