name: dash_design
description: Shared styles for Dart and Flutter websites.
version: 0.0.1-wip
publish_to: none
repository: https://github.com/dart-lang/site-shared/tree/main/pkgs/dash_design

resolution: workspace
environment:
  sdk: ^3.10.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  path: ^1.9.1
  sass: ^1.97.3
  test: ^1.28.0
