name: code_excerpter
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  build: ^2.4.0
  logging: ^1.1.1
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  build_runner: ^2.4.4
  test: ^1.23.0
