name: code_excerpter
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  build: ^2.2.1
  logging: ^1.0.2
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  test: ^1.20.0
